const nodemailer = require('nodemailer');

let transporter;

function getTransporter() {
  if (!transporter) {
    if (!process.env.SMTP_HOST) throw new Error('SMTP_HOST is not configured.');
    transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: parseInt(process.env.SMTP_PORT || '587', 10),
      secure: process.env.SMTP_SECURE === 'true',
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });
  }
  return transporter;
}

/**
 * Send an AI-generated sales brief to the recipient.
 * @param {string} to - Recipient email address
 * @param {string} htmlContent - HTML body of the email
 * @param {string} filename - Original uploaded filename
 */
async function sendSalesBrief(to, htmlContent, filename) {
  const transport = getTransporter();

  const mailOptions = {
    from: `"Sales Insight Automator 🤖" <${process.env.SMTP_USER}>`,
    to,
    subject: `📊 AI Sales Brief — ${filename} — ${new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`,
    html: `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <style>
          body { font-family: Georgia, serif; color: #1a1a2e; background: #f9f9f9; padding: 0; margin: 0; }
          .wrapper { max-width: 700px; margin: 40px auto; background: #ffffff; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden; }
          .header { background: #1a1a2e; color: #f0c040; padding: 28px 36px; }
          .header h1 { margin: 0; font-size: 22px; letter-spacing: 1px; }
          .header p { margin: 4px 0 0; font-size: 13px; color: #aaa; }
          .body { padding: 32px 36px; }
          h2 { color: #1a1a2e; border-bottom: 2px solid #f0c040; padding-bottom: 6px; margin-top: 28px; }
          table { width: 100%; border-collapse: collapse; margin: 16px 0; }
          th { background: #1a1a2e; color: #f0c040; padding: 10px 14px; text-align: left; font-size: 13px; }
          td { padding: 9px 14px; border-bottom: 1px solid #eee; font-size: 14px; }
          tr:nth-child(even) td { background: #f9f9f9; }
          ul { padding-left: 20px; } li { margin-bottom: 6px; line-height: 1.6; }
          p { line-height: 1.7; }
          .footer { background: #f0f0f0; padding: 16px 36px; font-size: 12px; color: #888; text-align: center; }
        </style>
      </head>
      <body>
        <div class="wrapper">
          <div class="header">
            <h1>📊 Sales Insight Brief</h1>
            <p>Generated by Rabbitt AI · ${new Date().toLocaleString()}</p>
          </div>
          <div class="body">
            ${htmlContent}
          </div>
          <div class="footer">
            This report was auto-generated from <strong>${filename}</strong> by the Sales Insight Automator.<br/>
            Rabbitt AI · Confidential — Internal Use Only
          </div>
        </div>
      </body>
      </html>
    `,
  };

  const info = await transport.sendMail(mailOptions);
  return info.messageId;
}

module.exports = { sendSalesBrief };
